### ISSUE TITLE
[Suggestion]: Link writers' Github profiles

### ISSUE THREAD

**Issue by docmars** [Layerful/programmar#1]
It'd be great to link to the GitHub profiles of users, especially if you like what they've written.

_Let me know if there's a better place to send/post suggestions or feedback._

**Comment by bobbygiangeruso** [comment]
Hey @docmars,

Thanks a lot for the suggestion. I've just designed for that feature now and should be seen online soon. What you're doing now is great for suggestions/feedback. We are also active on our Twitter at <a href="http://twitter.com/_programmar">@_programmar</a>, if that's easier for you.
