### ISSUE TITLE
[Suggestion]: Add comments or provide some discussion medium

### ISSUE THREAD

**Issue by docmars** [Layerful/programmar#2]
After reading an article, I really wanted to start a discussion with the author or get some kind of dialogue going on something he talked about. I think something that's really important within dev. communities is the ability to critique or optimize something further.

I'm not sure if commenting is on the roadmap, but it would be a welcome feature if done right. Of course, it isn't as easy as _just adding comments_. On the other hand, the way Medium implements them encourages discussion around certain pieces of an article, which could be nice for code snippets and other pieces.

**Comment by docmars** [comment]
Ah--just realized this was already in the roadmap posted on there.

**Comment by bobbygiangeruso** [comment]
Hey @docmars,

Commenting is definitely on the roadmap. We're going to build up a better list of what's coming next for us, which will appear in our GitHub documentation. A tweet will also follow along when the list is made. Thanks again for you suggestions!
