### ISSUE TITLE
code block displayed in excerpt

### ISSUE THREAD

**Issue by baptistebriel** [Layerful/programmar#6]
On the following page / list, the text wrapped into a `<code>` block shouldn't be displayed in the 
excerpt. :)
![screen shot 2015-09-28 at 16 28 58](https://cloud.githubusercontent.com/assets/2464663/10138275/09528d76-65fe-11e5-9842-0d268ceefcad.png)
Otherwise, great work! Looks cool.

**Comment by JosephSmith127** [comment]
Hey man thanks for the feedback. At first thoughts on doing this I just displayed everything, and just filtered out tags. But your method makes a lot more sense. I am going to update it now!

**Comment by JosephSmith127** [comment]
made it so that when your code article starts with a code block... meaning there is not a brief description of what you're showing them how to do... then it uses the tags for the "preview text" to give people better idea of whats involved :)

**Comment by baptistebriel** [comment]
Perfect! Closing this now. ;) 👍
