### ISSUE TITLE
@replies Point to Incorrect URL

### ISSUE THREAD

**Issue by daviddarnes** [Layerful/programmar#7]
Example: https://programmar.io/articles/3

Hitting the reply in the second comment sends the reader to the url `/users/username` when it should be `/user/username`.

A minor issue.

**Comment by JosephSmith127** [comment]
should be fixed good spot! thanks!

**Comment by daviddarnes** [comment]
:+1:

Ref: https://github.com/Layerful/programmar/commit/0e891efdd55f749256a3c6c8684be41d9312d874

**Comment by daviddarnes** [comment]
…fixed at 4am :interrobang:

**Comment by JosephSmith127** [comment]
go hard of go home :+1:
